# Generated by Django 4.1.3 on 2022-11-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0002_pregunta_justificacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prueba',
            new_name='Evaluacion',
        ),
    ]
