# Generated by Django 4.1.3 on 2022-11-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0003_rename_prueba_evaluacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacion',
            old_name='dificultad',
            new_name='nivel',
        ),
    ]
