# Generated by Django 4.1.3 on 2022-11-16 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0004_rename_dificultad_evaluacion_nivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='prueba',
            new_name='evaluacion',
        ),
    ]
