# Generated by Django 4.1.3 on 2022-11-17 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0005_rename_prueba_pregunta_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
