# Generated by Django 4.1.3 on 2022-11-17 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulador', '0006_evaluacion_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.evaluacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleIntento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(default=0)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.intentos')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.pregunta')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.respuesta')),
            ],
        ),
    ]
