# Generated by Django 4.1.3 on 2022-11-17 17:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulador', '0007_intentos_detalleintento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intentos',
            new_name='Intento',
        ),
    ]
