# Generated by Django 4.1.3 on 2022-11-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0010_alter_intento_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='tiempo',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='intento',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
